Add new color theme 'iroaseta'
helix-editor/helix pull request #10381
Opened 2024-04-13 11:44 UTC by YardQuit

Dark color theme with subdued text colors

2024-04-14 12:14 UTC, postsolar requested changes
Maybe you could also add "ui.virtual.jump-label"?

2024-04-14 12:14 UTC, postsolar commented on runtime/themes/iroaseta.toml
> +"condtant.builtin.boolean" = { fg = "blue" }
```suggestion
"constant.builtin.boolean" = { fg = "blue" }
```

2024-04-14 20:19 UTC, YardQuit commented
> Maybe you could also add "ui.virtual.jump-label"?
Thanks, this feature isn't present in the fedora 39 version yet. I absolutely what to add this with the modifiers = ["reversed"] setting. Can I do it from this pull request or do I need to work from my fork and redo the pull request? My first time doing this :)

2024-04-14 20:24 UTC, YardQuit commented
> > Maybe you could also add "ui.virtual.jump-label"?
> > Thanks, this feature isn't present in the fedora 39 version yet. I absolutely what to add this with the modifiers = ["reversed"] setting. Can I do it from this pull request or do I need to work from my fork and redo the pull request? My first time doing this :)

I believe I figured it out, the the setting should be in place now.

2024-04-14 20:27 UTC, postsolar approved these changes

2024-04-15 15:57 UTC, the-mikedavis commented on runtime/themes/iroaseta.toml
> +"constant.character.numeric.float" = { fg = "blue" }
```suggestion
"constant.numeric.integer" = { fg = "blue" }
"constant.numeric.float" = { fg = "blue" }
```

2024-04-15 15:57 UTC, the-mikedavis commented on runtime/themes/iroaseta.toml
> +"storage.modifier" = { fg = "yellow" }
```suggestion
"keyword.storage" = { fg = "red" }
"keyword.storage.type" = { fg = "red" }
"keyword.storage.modifier" = { fg = "yellow" }
```

these are nested under keyword

2024-04-16 13:03 UTC, the-mikedavis commented on runtime/themes/iroaseta.toml
> +"diagnostic" = { fg = "", bg = "#3d0c02", modifiers = ["default"] }
looks like the `fg` here is empty

2024-04-16 13:44 UTC, the-mikedavis commented on runtime/themes/iroaseta.toml
> +"diagnostic" = { fg = "yellow", bg = "#3d0c02", modifiers = ["default"] }
There isn't a `default` modifier, I think this can just be set to the empty list

2024-04-29 15:03 UTC, the-mikedavis commented on runtime/themes/iroaseta.toml
> +"ui.cursor.match" = { fg = "amber_shadow", bg = "blaze_orange", modifier = ["bold"] }                # matching bracket etc
```suggestion
"ui.cursor.match" = { fg = "amber_shadow", bg = "blaze_orange", modifiers = ["bold"] }               # matching bracket etc
```

2024-04-29 15:03 UTC, the-mikedavis commented on runtime/themes/iroaseta.toml
> +"diagnostick" = { modfiers = ["reversed"] }                                                          # diagnostics fallback style (editing area)
```suggestion
"diagnostic" = { modifiers = ["reversed"] }                                                          # diagnostics fallback style (editing area)
```

2024-04-30 14:56 UTC, the-mikedavis commented on runtime/themes/iroaseta.toml
> +"markup.raw" = { fg = "winter_sky" }
It looks like these colors aren't defined in the palette

2024-04-30 15:11 UTC, the-mikedavis approved these changes

2024-06-26 21:03 UTC, pascalkuthe approved these changes

2024-06-26 21:04 UTC, merged