Add Mail support
helix-editor/helix pull request #10667
Opened 2024-05-03 02:29 UTC by erasin

Close #4521
Mail Format [RFC-0822](https://www.ietf.org/rfc/rfc0822.txt)
Test File: <https://github.com/dagle/tree-sitter-mail/tree/main/test/corpus>

2024-05-03 10:49 UTC, mjholub commented
looks good! could you include screenshots?

2024-05-04 01:32 UTC, erasin commented
<img width="671" alt="截屏2024-05-04 09 31 22" src="https://github.com/helix-editor/helix/assets/716514/53afb43e-b532-4818-a0fb-f7c884c15e90">

2024-05-06 13:39 UTC, the-mikedavis requested changes
This grammar seems like a work-in-progress - the last commit was quite a while ago and seems unfinished. I don't have a problem merging a grammar that has a few bugs but this grammar also doesn't have a LICENSE and I'd like to not merge grammars that don't have those since it complicates downstream packaging

2025-08-22 01:45 UTC, erasin commented
#12945

2025-08-22 01:45 UTC, closed without merging