Update dependencies
helix-editor/helix pull request #11847
Opened 2024-10-07 16:16 UTC by StratusFearMe21

This PR updates `tree-sitter` and some other dependencies. `hashbrown` no longer has the `raw` feature, so I couldn't update that, but everything else should be up-to-date

2024-10-07 17:07 UTC, pascalkuthe requested changes

2024-10-07 17:08 UTC, pascalkuthe commented
While the tree sitter API changes are an I.provement I am not sure it's worth  upgrading at this point since we are switching to out own bindings

2024-10-07 17:10 UTC, StratusFearMe21 commented on helix-core/Cargo.toml
> -unicode-width = "=0.1.12"
Aaa, I'll revert that

2025-02-18 17:25 UTC, StratusFearMe21 commented
Any status on the new `tree-sitter` bindings? Is that still the plan?

2025-02-18 21:24 UTC, closed without merging

2025-02-18 21:24 UTC, the-mikedavis commented
Yeah, they're pretty close - I've been focused on them for the last two weeks or so and I have an initial integration branch nearly ready. The changes there will drop our dependency on the `tree-sitter` crate and, conveniently, also remove the use of `hashbrown::RawTable`. I will close this out since we will want to switch directly to the new highlighter (rather than pulling in streaming_iterator) but thanks for taking a look at these updates!

2025-02-19 17:17 UTC, StratusFearMe21 commented
Awesome can't wait to see the new bindings 😄 !