Add partial scala syntax highlights
helix-editor/helix pull request #1278
Opened 2021-12-16 12:25 UTC by dwat3r

Hi!

I really like helix, so I'd like to add scala syntax highlight and LSP support for it.
Amazingly, LSP support with metals works out-of-the-box, although additional metals commands like import build and others obviously needs to be added. 

I've copied the tree-sitter highlights and injections from nvim-treesitter, but found a couple of issues with it, and couldn't figure out it yet, so the syntax highlighting is partial currently. I'm happy to receive suggestions how to migrate the whole from nvim.

2021-12-16 15:04 UTC, archseer requested changes

2021-12-16 15:04 UTC, archseer commented on runtime/queries/scala/highlights.scm
> +] @conditional
@keyword.conditional

2021-12-16 15:04 UTC, archseer commented on runtime/queries/scala/highlights.scm
> +  (case_clause ("case") @conditional))
`@keyword.conditional`

2021-12-16 21:14 UTC, amousset commented
I checked open PR before starting https://github.com/helix-editor/helix/pull/1279 and it happened to be the day another identical PR is opened :smile: 

To make syntax highlighting work I had to update the tree-sitter-scala submodule.

2021-12-17 07:45 UTC, archseer requested changes

2021-12-17 07:45 UTC, archseer commented on runtime/queries/scala/highlights.scm
> +    field: (identifier) @method))
`@function.method`

2021-12-17 07:45 UTC, archseer commented on runtime/queries/scala/highlights.scm
> +  name: (identifier) @parameter)
`@variable.parameter`

2021-12-17 07:45 UTC, archseer commented on runtime/queries/scala/highlights.scm
> +(field_expression field: (identifier) @property)
`@variable.other.member`

2021-12-17 07:45 UTC, archseer commented on runtime/queries/scala/highlights.scm
> +(symbol_literal)
`symbol_literal` could be `@string.special.symbol`

2021-12-17 07:45 UTC, archseer commented on runtime/queries/scala/highlights.scm
> +]  @punctuation.bracket
```suggestion
] @punctuation.bracket
```

2021-12-17 07:45 UTC, archseer commented on runtime/queries/scala/highlights.scm
> +"import" @include
`@keyword.control.import`

2021-12-17 07:45 UTC, archseer commented on runtime/queries/scala/highlights.scm
> +  (case_clause ("case") @keyword.conditional))
```suggestion
  (case_clause ("case") @keyword.control.conditional))
```

2021-12-17 07:45 UTC, archseer commented on runtime/queries/scala/highlights.scm
> +  "match"
```suggestion
 "else"
 "if"
 "match"
```

2021-12-17 08:18 UTC, dwat3r commented
> I checked open PR before starting #1279 and it happened to be the day another identical PR is opened smile
> 
> To make syntax highlighting work I had to update the tree-sitter-scala submodule.
Thanks, this was also required to make scala syntax highlight work :) 

I've corrected the syntax, but I'm not sure why helix doesn't color things like objects and other stuff like neovim with the nvim-treesitter.

Here's a comparison screenshot (both are using their own onedark theme (hx: builtin, nvim: ful1e5/onedark.nvim)):
With neovim treesitter:
![scala-nvim](https://user-images.githubusercontent.com/6506116/146512033-9571bdc0-92c3-4dfa-9d10-3ecf775556ff.png)
helix with this PR:
![scala-helix](https://user-images.githubusercontent.com/6506116/146512036-9482b264-6278-4b6a-af0e-6de7fc84fd55.png)

Also apologies for spoiling some old advent of code for you :D

2021-12-17 12:55 UTC, archseer commented
It's probably the theme definitions not being defined for every syntax scope. I actually prefer it this way because it strikes a nice balance (is it really necessary to highlight **_every_** word? Not a single word in the first image isn't highlighted..)

I'll do some debugging locally though.

2021-12-17 13:00 UTC, archseer commented on runtime/queries/scala/highlights.scm
> +(identifier) @variable
Move this to the end of the file. tree-sitter takes the first matching query, and this matches and overrides a lot of the later queries.

It significantly improved highlighting for me: 
![pos](https://user-images.githubusercontent.com/1372918/146548243-534058c1-65be-4fe1-95c5-3b1a93a4d8c7.png)

2021-12-17 13:01 UTC, archseer commented on runtime/queries/scala/highlights.scm
> +(symbol_literal) @string_special_symbol
`@string.special.symbol`

2021-12-17 13:43 UTC, dwat3r commented
You're right, too much highlight is not very good. Although I've missed the functions being highlighted, but your fix made it perfect! :)

2021-12-18 04:40 UTC, merged