feat(languages): Elm
helix-editor/helix pull request #1514
Opened 2022-01-14 21:40 UTC by jaredramirez

Hey there,

This PR adds support for [Elm](https://elm-lang.org/)!

2022-01-15 15:12 UTC, pickfire commented
```
cargo xtask docgen
```

2022-01-16 01:17 UTC, archseer requested changes

2022-01-16 01:17 UTC, archseer commented on runtime/queries/elm/highlights.scm
> +(string_escape) @constant.character
`@constant.character.escape`

2022-01-16 01:17 UTC, archseer commented on runtime/queries/elm/highlights.scm
> +(glsl_content) @source.glsl
You can remove this, it's handled by injections

2022-01-16 01:17 UTC, archseer commented on runtime/queries/elm/highlights.scm
> +(import) @keyword.other
`@keyword.control.import`

2022-01-16 01:17 UTC, archseer commented on runtime/queries/elm/highlights.scm
> +"}" @punctuation.braces
```suggestion
[
  "("
  ")"
  "["
  "]"
  "{"
  "}"
] @punctuation.bracket
```

2022-01-19 06:26 UTC, kevinsjoberg commented
This looks ready, right?

2022-01-20 04:27 UTC, jaredramirez commented
Friendly ping @archseer 😃

2022-01-20 05:09 UTC, the-mikedavis approved these changes
this one lgtm too 🎉

2022-01-20 15:47 UTC, merged