Add swift language
helix-editor/helix pull request #2033
Opened 2022-04-08 17:43 UTC by Dispersia

https://github.com/helix-editor/helix/issues/1964

 Was also planning on using this, so went ahead and implemented it. From that issue, I forked the current tree-sitter-swift and checked in the current build configs, until a better solution is implemented (if we just want to wait if they want to add a separate branch, that's fine too).

 There are a few keywords that are in the highlights.scm that I didn't see in https://docs.helix-editor.com/themes.html#syntax-highlighting, so I didn't know how to handle them and just left them as is.

 Finally, there is one issue in swift I can't seem to figure out.

![image](https://user-images.githubusercontent.com/7254623/162494012-c82f83e5-0f76-4cae-835e-0cd85994ec5d.png)

when tabbing through, it's auto appending the parenthesis, but puts the cursor outside so you have to backspace. Is there a way to prevent this I didn't see?

2022-04-08 17:51 UTC, the-mikedavis requested changes
this is looking good, just a few scopes need adjustment

2022-04-08 17:51 UTC, the-mikedavis commented on runtime/queries/swift/highlights.scm
> +] @number
```suggestion
(integer_literal) @constant.numeric.integer
[
 (hex_literal)
 (oct_literal)
 (bin_literal)
] @constant.numeric
```

2022-04-08 17:51 UTC, the-mikedavis commented on runtime/queries/swift/highlights.scm
> +(import_declaration ["import" @include])
```suggestion
(import_declaration ["import" @keyword.control.import])
```

2022-04-08 17:51 UTC, the-mikedavis commented on runtime/queries/swift/highlights.scm
> +(protocol_property_declaration (value_binding_pattern (non_binding_pattern (simple_identifier) @property)))
```suggestion
(class_body (property_declaration (value_binding_pattern (non_binding_pattern (simple_identifier) @variable.other.member))))
(protocol_property_declaration (value_binding_pattern (non_binding_pattern (simple_identifier) @variable.other.member)))
```

2022-04-08 17:53 UTC, the-mikedavis commented
w.r.t. the lsp, I've seen similar behavior from erlang-ls, it will auto-complete arguments as well, so

```erl
maps:get| %% hit tab when cursor is on |
%% becomes
maps:get(Arg1, Arg2)|
```

I haven't dug into it further but I think it's behavior on the language server side. Maybe those language servers implement an outdated version of the spec.

2022-04-08 17:54 UTC, the-mikedavis commented
oh, also please run `cargo xtask docgen` and commit the results of that (will clear up the :x: for the Docs ci)

2022-04-08 18:02 UTC, Dispersia commented
thanks, updated the PR, and that makes sense. I'm going to try to look into that issue further, but it auto completes significantly more (even inlines the parameter name) which I haven't seen other LSP's do

2022-04-08 18:10 UTC, the-mikedavis approved these changes
nice work, thanks!

2022-04-08 18:10 UTC, merged

2022-04-08 19:29 UTC, the-mikedavis commented
@Dispersia for erlang-ls this issue has some discussion on it: https://github.com/erlang-ls/erlang_ls/issues/772. From the discussion there it sounds like there's a "snippets" approach to doing autocomplete. I'll dig into this more but that might be a good hint for swift as well.

2022-04-08 19:30 UTC, the-mikedavis commented
Also would you mind adding a quick note to the new lsp wiki for sourcekit-lsp? https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers

2022-04-08 19:47 UTC, Dispersia commented
Added to the wiki, and appreciate the link, that will definitely help!

2022-04-09 20:36 UTC, Dispersia commented
Finally understand why it does this. I don't know if helix supports snippets (or if it's a standardized thing, or it's a vscode thing), but what happens is in sourcekit-lsp they do this:
https://github.com/apple/sourcekit-lsp/blob/27956e6d6f029afcdeb3c151400d720270b40a2c/Sources/SourceKitLSP/Swift/CodeCompletion.swift#L205

Text returned from sourcekitd comes in as something such as `append(<#T##contentType: #ContentType#String#>), however the server relays if it supports snippets or not. If it does support snippets, the line linked above replace the above content with `append(contentsOf: ${1:Sequence})`. When testing with VSCode, if that comes back in the edit response it puts the cursor over the text "Sequence" and has the entire word selected. If server says snippets aren't supported, it simply deletes the text except `contentType:` in this case, but it's just normal text so puts your cursor at the end, like it should.

 I don't know if this is something that's want to be supported (trying to find if that's specific to vscode or it's part of an actual spec), but going to make the recommendation to remove all of it if snippets aren't supported to sourcekit-lsp's working group

2022-04-09 20:48 UTC, the-mikedavis commented
Ah makes sense! That's what I found with the Erlang LS as well (https://github.com/erlang-ls/erlang_ls/pull/1263). There's a PR for snippets support in helix (https://github.com/helix-editor/helix/pull/1178) but it seems like a pretty complicated feature and the PR appears to have paused.

IMO language servers should not auto-complete past the function name - not even the parens because that would mess up auto-pairs - because you have to edit backwards to deal with the generated stuff. Plus it kinda bumps with signature help (https://github.com/helix-editor/helix/pull/1755)

2022-04-09 20:57 UTC, Dispersia commented
Funny they both do the same thing, and we both came to the same conclusion of what should actually happen haha. Will wait to see their response, hopefully they agree 😄

2024-02-03 01:12 UTC, 7ombie commented
Nice to see Swift supported (Xcode is horrible). However, the syntax highlighting is only partially functional. Types are only highlighted when they're used as type annotations, which is not how Swift is conventionally highlighted (in Xcode, at least, which uses the same logic). Take the following example:

```
let x: Float = 1
let y = Float(1)
```

The annotation (the `Float` on Line 1) is highlighted in Helix, but the `Float` on Line 2 isn't.

In the following example, `MemoryLayout` and `Int` should be highlighted as types, but are not highlighted at all:

```
let stride = MemoryLayout<Int>.stride
```

On the other hand, the type (`SpaceInvader`) *is* highlighted (as a type despite not being an annotation) in this example:

```
let invader = SpaceInvader.staticMember
```

So, it's not even consistent.

The `try` keyword is highlighted as an operator (along with a bang that follows it).

The `?` and `!` operators are generally highlighted inconsistently. It seems that `?` is highlighted as if it's a type, while `!` is not highlighted at all (it's not an operator, except in the context of `try!`).

I use minimal highlighting, so am not sure what else is missing, but noticed that enums do not reflect the style bound to `type.enum` (and there's no other `enum` scope). Not sure if that's intentional.

2024-02-03 01:21 UTC, Dispersia commented
This is two years old, have you tried updating the comment and changing the config? I'm sure it supports all of the new syntax and has a lot of improvements, it looks fairly active and gets updated weekly

2024-02-03 02:29 UTC, 7ombie commented
Updating which comment?

Changing which config? I'm using the Swift support that is included with Helix (with SourceKit LSP). I'm not sure what else I'm meant to use??

What gets updated weekly? Swift support?? It's not very mature, if that's the case.

If you're not using it, I guess it's not your problem anymore. I appreciate you taking the time to reply still. All the best.

2024-02-06 00:34 UTC, 7ombie commented
Thank you, @Dispersia. I see. I can't commit to doing it right now, but I am keen to improve Swift support, and to begin contributing to Helix. I don't know Rust, but could help with the Swift grammar etc.

> should be fairly simple to open a PR for it if you're interesting in updating the grammars, and if you run into any issues feel free make an issue and we can discuss it

Will do. Thanks again. All the best.

2024-02-07 00:46 UTC, 7ombie commented
I'm just looking into this a bit more. I think I get most of it, but am unsure on what to commit to (to get the updated ID). I installed Helix with `brew`, so the files are in `/opt/homebrew/Cellar/helix/23.10/`, and I don't want to confuse Homebrew (which uses `git` too).

I can reinstall Helix manually, and build it from source, but even then, I'm not sure if I'm supposed to commit to Helix or to a Swift-specific repo (after I update the `scm` files)??

I'd appreciate any guidance. Thanks again.

2024-02-07 01:14 UTC, Dispersia commented
the updated id is just whatever the latest commit on their branch is, so https://github.com/alex-pinkus/tree-sitter-swift latest (as of me posting this message) is 1c586339fb00014b23d6933f2cc32b588a226f3b

you'll be commiting to helix, with changes to this directory: https://github.com/helix-editor/helix/tree/master/runtime/queries/swift with changes from theirs for the files i had listed above

and ya, you will need to build it locally, as you will need to update the languages.toml, which is built into the executable (but you wont touch any rust code, just configurations)

2024-02-07 01:25 UTC, 7ombie commented
Thank you, @Dispersia. Much appreciated. I'll give it a go.

2024-02-08 03:15 UTC, 7ombie commented
Sorry to be a pain. I'm a bit stuck.

I cloned TreeSitter and Helix, set `HELIX_DEFAULT_RUNTIME` to the `runtime` directory inside the repo, then built Helix from source. That seemed to work fine. Helix found its grammars etc, as well my `~/.config/helix` (which does not contain a `runtime` directory).

I then edited `.../runtime/queries/swift/highlights.scm` within the Helix repo, making a few changes, based on the tree-sitter version (TreeSitter's `highlights.scm` hasn't evolved much, and I figured I could focus on the other SCM files later). I also updated `languages.toml` to point to the newest commit hash for TreeSitter (which was still the one you posted).

When I tried to rebuild Helix (using `cargo install --path helix-term --locked`) it failed with this message:

```
  Failure 1/1: swift Failed to compare source and binary timestamps

  --- stderr
  thread 'main' panicked at 'Failed to compile tree-sitter grammars: 1 grammars failed to build', helix-term/build.rs:7:14
```

At first I thought my mistake was not committing the changes I'd made to Helix, so I added the changes and made a new commit, and saw the changes to the two files (`.../swift/highlights.scm` and `languages.toml`) reported by `git`. When I went to rebuild Helix, I got the same error again, and don't know how to proceed.

Sorry to keep bothering you @Dispersia. Is there somewhere better I can ask for help with this? Thanks again.

2024-02-08 11:55 UTC, 7ombie commented
I'll open a new issue, @Dispersia. It's not really fair to expect you to onboard me (no good deed goes unpunished, ay). Best wishes. Thanks again. You've been awesome.