feat(lang): add Meson language support
helix-editor/helix pull request #2314
Opened 2022-04-28 21:45 UTC by unrelentingtech

https://mesonbuild.com/Syntax.html
https://github.com/bearcove/tree-sitter-meson

![Screen_2022-04-29-00:44:17](https://user-images.githubusercontent.com/208340/165851390-aae740f5-955d-4901-82cf-e944df3c8c94.png)

2022-04-28 23:29 UTC, the-mikedavis requested changes
Couple of minor things but looks good otherwise 👍 

Let's await https://github.com/bearcove/tree-sitter-meson/issues/3 too

2022-04-28 23:29 UTC, the-mikedavis commented on runtime/queries/meson/highlights.scm
> +(keyword_arg_key) @property
```suggestion
(keyword_arg_key) @variable.other.member
```

2022-04-28 23:29 UTC, the-mikedavis commented on runtime/queries/meson/highlights.scm
> +(integer_literal) @constant.builtin.numeric.integer
```suggestion
(integer_literal) @constant.numeric.integer
```

2022-05-02 14:29 UTC, archseer approved these changes
Looks good, but can you resolve the merge conflict?

2022-05-08 16:10 UTC, unrelentingtech commented
rebased again

2022-05-11 01:06 UTC, merged