feat(languages): add odin language
helix-editor/helix pull request #2399
Opened 2022-05-04 16:38 UTC by RobWalt

This commit adds the odin language by using the grammar and highlighting
queries written by [MineBills repo](https://github.com/MineBill/tree-sitter-odin).

This commit resolves #2340 by just applying all the changes already
discussed in the issue.

2022-05-04 16:39 UTC, RobWalt commented
+ I tested the functionality with the example also located in [MineBills repo](https://github.com/MineBill/tree-sitter-odin) and it worked on my machine perfectly fine.

2022-05-04 18:11 UTC, the-mikedavis commented
If you run `cargo xtask docgen` and commit the results it'll clear up the :x: from the Docs CI

2022-05-04 18:14 UTC, the-mikedavis requested changes
a few suggested changes here to bring the captures in line with the ones helix uses: https://github.com/helix-editor/helix/blob/f1a77370cf679eb0f3a58cfb12deec8ff7fc6325/book/src/themes.md#syntax-highlighting

2022-05-04 18:14 UTC, the-mikedavis commented on runtime/queries/odin/highlights.scm
> +(field_identifier) @property
```suggestion
(field_identifier) @variable.other.member
```

2022-05-04 18:14 UTC, the-mikedavis commented on runtime/queries/odin/highlights.scm
> +(escape_sequence) @escape
```suggestion
(escape_sequence) @constant.character.escape
```

2022-05-05 16:55 UTC, RobWalt commented
Hey, I just looked into your review. Sorry for adding the queries so carelessly. I think I understand the purpose of the file a bit better now. All of your suggested changes make sense.

2022-05-05 17:03 UTC, RobWalt commented on runtime/queries/odin/highlights.scm
> +] @constant
I changed `true` and `false` to be of type `@constant.builtin.boolean` and used your suggestion for the rest

2022-05-05 17:08 UTC, the-mikedavis commented
No worries, queries typically need a bit of tuning anyways 😄

2022-05-05 17:09 UTC, the-mikedavis approved these changes
Looks good. Thanks!

2022-05-05 17:09 UTC, merged

2022-05-12 12:34 UTC, spindlebink commented
Highlighting still isn't working for me, although it seems like Helix is recognizing `.odin` files correctly and Helix lists the Odin grammar as being both fetched and compiled. Also, I'm not aware of an explicit Odin styleguide, but the Odin project itself uses tabs for indentation, so the default indentation mode should probably be set accordingly.

2022-05-12 13:00 UTC, the-mikedavis commented
> Highlighting still isn't working for me

Check out `hx --health odin`. If it shows that you don't have highlight queries then you'll need to link your runtime directory: https://github.com/helix-editor/helix/blob/7b287f636f72766356aadb95ba2f32636e0601d3/README.md?plain=1#L52-L55

> the Odin project itself uses tabs for indentation

Would you like to submit a PR to change it? If Odin itself uses tabs it probably makes sense to set tabs as the default (and then it can be overridden on a per-project basis with #1249).