Only highlight inner area of view with cursorline
helix-editor/helix pull request #2935
Opened 2022-07-01 13:19 UTC by A-Walrus

Fixes #2912

2022-07-01 13:49 UTC, archseer requested changes

2022-07-01 13:49 UTC, archseer commented on helix-term/src/ui/editor.rs
> +                view.inner_area().width,
`let inner_area = view.inner_area()` before this line. Otherwise you're calculating it three times.

2022-07-16 17:01 UTC, sudormrfbin approved these changes

2022-07-18 01:15 UTC, archseer commented
I actually like the current behavior though.

2022-07-18 12:12 UTC, ChrHorn commented
> I actually like the current behavior though.

With this PR it is still possible to set `ui.linenr.selected` background color same as cursorline to achieve the current behavior (minus the diagnostics and the gap).

2022-07-22 07:27 UTC, archseer commented
Yeah it's not the same, it won't highlight all the gutters.

2022-07-23 06:58 UTC, ChrHorn commented
> Yeah it's not the same, it won't highlight all the gutters.

I see. What if we just use `ui.linenr(.selected)` for the whole gutter and rename it to `ui.gutter(.selected)` (`ui.gutter` is already used but not documented). Think this looks better in general and would allow both styles for the cursorline.

Could also use a more fine-grained approach where every selected component can be themed, but I'm not sure if this is really needed.

2022-08-02 03:05 UTC, archseer commented
`ui.gutter.selected` is a good idea, but I'd also keep `ui.linenr.selected` so that only the line number foreground can be changed.

2024-04-13 23:18 UTC, pascalkuthe commented
closing this one out as stale, the entire rendering code has been replaced (and will see further large changes) so it would be easier to start over with this one. Thank ou for contributing!

2024-04-13 23:18 UTC, closed without merging