added onedarker theme
helix-editor/helix pull request #3980
Opened 2022-09-26 13:32 UTC by Ziaft

2022-09-26 19:51 UTC, AlexanderBrevig requested changes
Please attach a screenshot to your description, and maybe a sentence or two about the theme?

2022-09-26 19:51 UTC, AlexanderBrevig commented on runtime/themes/onedarker.toml
> +"markup.link.text" = { fg = "purple" }
`markup.link.label` missing

2022-09-26 19:51 UTC, AlexanderBrevig commented on runtime/themes/onedarker.toml
> +"markup.raw.inline" = { fg = "green" }
`markup.raw.block` missing

2022-09-27 07:35 UTC, AlexanderBrevig approved these changes
LGTM

2022-09-30 23:30 UTC, the-mikedavis commented on runtime/themes/onedarker.toml
> +# Author : Gokul Soumya <gokulps15@gmail.com>
This should be replaced

2022-10-01 05:01 UTC, Ziaft commented on runtime/themes/onedarker.toml
> +# Author : Gokul Soumya <gokulps15@gmail.com>
Oh,  shoot, thank you

2022-10-01 14:11 UTC, the-mikedavis approved these changes

2022-10-01 14:11 UTC, merged

2022-10-01 14:11 UTC, the-mikedavis commented
Could you add a screenshot of this to the themes wiki? https://github.com/helix-editor/helix/wiki/Themes

2022-10-01 14:13 UTC, nuid32 commented
ok