Find out comment style from file content as a fallback
helix-editor/helix pull request #5386
Opened 2023-01-03 16:58 UTC by semin-park

Usually we find out the language based on file extension and use the comment style used for the language. This PR lets helix figure out the correct comment style by peeking the first few lines of the file. This is a fallback, when helix is unable to figure out the language for any reason.

fixes #5380

2023-01-03 21:18 UTC, the-mikedavis requested changes
It looks like this tries to determine the full language config from only the comment token. For common comment tokens like `//` or `#` this will most likely determine the wrong language and give confusing syntax highlighting

2023-01-04 15:55 UTC, kirawi commented
An alternative I would propose is to guess the comment style without setting a language for the file.

2023-03-26 07:46 UTC, Schweber commented
> An alternative I would propose is to guess the comment style without setting a language for the file.

This would be very helpful with .config files with arbitrary rules. I was going to suggest such a feature when i found this PR.

Could this please be implemented?

2024-04-13 23:24 UTC, pascalkuthe commented
clsoing this one out as stale as there are still unadressed review comments. Thank you for contributing!

2024-04-13 23:24 UTC, closed without merging