Language support for Angular
helix-editor/helix pull request #5607
Opened 2023-01-20 07:27 UTC by hunterliao29

close #4861

2023-01-21 19:09 UTC, the-mikedavis requested changes

2023-01-21 19:09 UTC, the-mikedavis commented on languages.toml
> +file-types = ["ts", "html"]
These will conflict with the typscript and html file-types: all `.ts` and `.html` files will become angular and will use this language server configuration. See https://github.com/helix-editor/helix/pull/3249

2023-01-21 20:37 UTC, hunterliao29 commented
I think this is not feasible due to the limitation.
#2507 to use angular, typescript, html, css language server.
#3249 to set file type
And need to have option to set language server base on file type.

2023-01-22 22:22 UTC, closed without merging

2023-10-31 12:28 UTC, danriedl commented
Hey @hunterliao29, asking in favor of https://github.com/helix-editor/helix/issues/4861.
As we do have now support for multiple language-servers could we reopen this, to get angular support?