Use doc.path() instead of doc.relative_path() for the buffer picker
helix-editor/helix pull request #634
Opened 2021-08-20 19:14 UTC by kirawi

Resolves #619

Not sure if `buffers_remaining_impl` also needs to be similarly changed.

2021-08-21 00:36 UTC, archseer requested changes
format_fn should still display path as relative

2021-08-21 00:36 UTC, archseer commented on helix-term/src/commands.rs
> -            .map(|(id, doc)| (id, doc.relative_path()))
doc.path().cloned()

2021-08-22 04:24 UTC, kirawi commented
Ah, I'll get it ready to merge tomorrow. Forgot one thing.

2021-08-24 00:57 UTC, archseer commented
I wrote an alternative in https://github.com/helix-editor/helix/commit/1d45f50781f34bccf29a3e4f576cc48651038b09

2021-08-24 00:57 UTC, closed without merging