ocaml support
helix-editor/helix pull request #666
Opened 2021-08-27 14:23 UTC by oberblastmeister

ocaml doesn't support comments to the end of the line. Might need to add a new comment type

2021-08-28 01:30 UTC, archseer requested changes

2021-08-28 01:30 UTC, archseer commented on .gitmodules
> +    shallow = true
Different indent, I think you used spaces instead of tabs?

2021-08-28 01:30 UTC, archseer commented on runtime/queries/ocaml/highlights.scm
> +; Modules
Upstream provides a `locals.scm`, can you include that too?

2021-08-28 01:30 UTC, archseer commented on runtime/queries/ocaml/highlights.scm
> +["if" "then" "else"] @conditional
`@keyword.control.conditional` (need to tweak this in the julia grammar too)

2021-08-28 01:30 UTC, archseer commented on runtime/queries/ocaml/highlights.scm
> +["for" "to" "downto" "while" "do" "done"] @repeat
`@keyword.control.loop`

2021-08-28 01:30 UTC, archseer commented on languages.toml
> +scope = "source.ocaml-interface"
I would use a dot to delineate. `source.ocaml.interface`

2021-08-28 01:30 UTC, archseer commented on runtime/queries/ocaml/highlights.scm
> +["exception" "try"] @exception
`@keyword.control.exception` (need to tweak this in the julia grammar too)

2021-08-28 01:31 UTC, archseer commented
The ocaml grammar provides a locals.scm too, can you include that?

2021-09-01 11:53 UTC, oberblastmeister commented
I add `locals.scm`. Some questions, what is `locals.scm` for? What is the `scope` key in `languages.toml` for?

2021-09-01 12:05 UTC, oberblastmeister commented
Also, what is injection regex

2021-09-01 13:13 UTC, archseer commented
- locals.scm see: https://tree-sitter.github.io/tree-sitter/syntax-highlighting#local-variables
- injection-regex: 
  >  A regex pattern that will be tested against a language name in order to determine whether this language should be used for a potential language injection site. Language injection is described in more detail in a later section.
  https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection

2021-09-01 13:18 UTC, oberblastmeister commented
there seems to be an issue when overriding highlights. For example,  there seems to be some weirdness in the highlight.scm. 
For example if i say all `(value_name)` is `@variable`, and I say
```
(application_expression
  function: (value_path (value_name) @function))`
```
I would expect the value_name to be overriden and be a function now

except it is not overriden and is not highlighted correctly

2021-09-01 13:34 UTC, oberblastmeister commented
thats fixed now, top to bottom worked

2021-09-01 16:01 UTC, archseer approved these changes

2021-09-01 16:08 UTC, merged

2021-09-01 21:20 UTC, starbuckbok commented
I had no idea that ocaml bows to the antichrist. Better steer away...