Refactor register.rs
helix-editor/helix pull request #6820
Opened 2023-04-19 16:24 UTC by CcydtN

Background
---
I am planning to work on #2038 and #6039. which are both related to registers and clipboard. However, I think the two enhancement will be hard to implement without changing the design of registers, so I work on the register first.

Changes
---
Register become a trait, so different kinds of register can store in a single table, but handle input differently.
`SimpleRegister` is same as the original `Register`
`HistoryRegister` provide the old `Register::push()` function
`BlackHoleRegister` to avoid the "hardcode if" for the underscore(_) register
> For `HistoryRegister`
Before refactoring, `"`,`/`,`:`register was overwrite when yank (e.g`"/y`). After refactoring, it will become append instead of overwrite.

2023-04-19 18:09 UTC, CcydtN commented
Follow up issue: (discovered while development)
- [ ] History register can store infinite record (up to vector limit), should consider giving a fixed limit (exist in before this commit)
- [ ] `/` and `:` register, should show the latest item for history register, currently showing the oldest one (exist before this commit)

2023-04-19 23:21 UTC, the-mikedavis requested changes
Normal registers shouldn't have different backends. `/`, `"` and `:` are not special registers but just default registers used by some commands. You should be able to use any other register by using `"<reg>` before that command, for example `"/y` to yank the current selections into the search register. Whether a register is "simple" or "history" is should be decided by how a command uses the register rather than which data structure the register is.

2023-04-20 01:25 UTC, CcydtN commented
Could you elaborate more on the case of searching or enter a command?

In those case, should we overwrite the register? or appending?

2023-04-20 02:06 UTC, archseer commented
I'm also not sure we want #6039 implemented, it's not an option available in vim

2023-04-20 04:39 UTC, CcydtN commented
> I'm also not sure we want #6039 implemented, it's not an option available in vim

In vim, i think it can be done by setting the default register to '+' or '*' which is the clipboard register.

2023-04-20 21:30 UTC, the-mikedavis commented
Searching and entering commands should append to whichever register is being used. That's done here in the Prompt: https://github.com/helix-editor/helix/blob/b336cd76a740eea6ea41baa1028233ccf6e12ee5/helix-term/src/ui/prompt.rs#L570-L573

System clipboard yanking is less powerful than register yanking since the clipboard can't support multiple values which is used for yanking/pasting multiple selections in Helix. So I agree with archseer, I don't think we should add #2038 or #6039 - those should be possible to do with keybinding and we don't want extra options where keybindings are sufficient, especially ones that reduce the functionality of a feature.

2023-04-21 21:52 UTC, CcydtN commented
System clipboard yanking and paste with multiple selection should be possible. Here is [a draft](https://github.com/CcydtN/helix/blob/clipboard_register/helix-view/src/clipboard_register.rs). If the hash didn't change, it means the content comes from helix, and can be pasted with multiple cursor.

For the two register `:`,`/`, I still think they are weird. Right now, they are having two different function with one data structure. The inner vector can be history records, and also selections from multiple cursor. One of the consequence is that history record gets clear when yank to register. Vim tackle the problem by making them read-only.

An other approach might be storing history in another variable. We can still store the last search in the register, but with no history.

2023-04-24 18:21 UTC, the-mikedavis commented
I think that could be a good strategy regardless of #2038 / #6039. I'm still against implementing those two. That change doesn't need this refactor or a new ClipboardRegister type though. It can be done more minimally with changes in `paste_clipboard_impl`, new fields on Editor for the value and hash, and a new function that yanks all selections to the clipboard.

2023-04-25 16:49 UTC, CcydtN commented
Alright, I am giving up this idea. I will close this pull request and will make another pull request for the multiple-selection yank function and other minor issue I motioned on top. 

Anyway, thanks for your opinion. @the-mikedavis

2023-04-25 16:49 UTC, closed without merging

2024-02-26 22:57 UTC, Abdillah commented
> I don't think we should add #2038 or #6039 - those should be possible to do with keybinding and we don't want extra options where keybindings are sufficient, especially ones that reduce the functionality of a feature.

On the note of #6039, combining `yank` and "yank to system clipboard" actually failed.