document macros
helix-editor/helix pull request #693
Opened 2021-09-01 17:37 UTC by oberblastmeister

2021-09-01 17:52 UTC, kirawi requested changes
I would simplify the block of text into something like:
`//! Macros to partially borrow \`Editor\`, until https://github.com/rust-lang/rfcs/issues/1215.`

I think that as it is currently, it's very confusing and is over explaining what these macros used for.

2021-09-01 17:52 UTC, kirawi commented on helix-view/src/macros.rs
> +//! These are macros to make getting very nested fields in the `Editor` struct easier
You should end the sentences with a period.

2021-09-01 17:52 UTC, kirawi commented on helix-view/src/macros.rs
> +//! entire struct which `&mut self` says.  This makes it impossible to do other mutable
Double space after a period.

2021-09-01 17:52 UTC, kirawi commented on helix-view/src/macros.rs
> +//! putting a &mut in front of it. This way rust can see that we are only borrowing a
rust -> Rust

2021-09-03 01:53 UTC, pickfire commented on helix-view/src/macros.rs
> +//! putting a &mut in front of it. This way rust can see that we are only borrowing a
```suggestion
//! putting a `&mut` in front of it. This way rust can see that we are only borrowing a
```

2021-09-05 03:42 UTC, archseer approved these changes

2021-09-05 03:42 UTC, merged