Update languages.toml for Nickel
helix-editor/helix pull request #7059
Opened 2023-05-17 15:01 UTC by vkleen

Update the revision of `tree-sitter-nickel` and copy over the highlighting queries. Also, adjust the `auto-pairs` configuration, since `'` isn't a paired delimiter in Nickel.

2023-05-17 19:55 UTC, ErinvanderVeen submitted a review, later dismissed

2023-05-18 01:18 UTC, the-mikedavis requested changes

2023-05-18 01:18 UTC, the-mikedavis commented on runtime/queries/nickel/highlights.scm
Are these copied over from tree-sitter-nickel? They look like they're used in nvim-treesitter: you can remove the `@spell` captures and some of the other captures need to be renamed to align with the capture names that [Helix uses](https://docs.helix-editor.com/master/themes.html#syntax-highlighting) (for examples, `conditional` should become `keyword.control.conditional`, `boolean` should become `constant.builtin.boolean`, etc.)

2023-05-19 09:56 UTC, vkleen commented on runtime/queries/nickel/highlights.scm
These were indeed copied over from tree-sitter-nickel. I've restored the original ones from helix and tried to update what's necessary for the changes in tree-sitter-nickel.

2023-05-19 23:15 UTC, the-mikedavis submitted a review, later dismissed
Thanks!

2023-05-19 23:34 UTC, pascalkuthe commented
Seems like CI is failing with some identity query related error. Seems like those also need to be updated before we can merge

2023-05-20 00:25 UTC, the-mikedavis commented
Ah yeah it looks like the `switch_expr` node doesn't exist in this version (https://github.com/helix-editor/helix/actions/runs/5023053043/jobs/9020326641?pr=7059). It looks like it may be `match_expr` now https://github.com/nickel-lang/tree-sitter-nickel/blob/3a794388773f2424a97b2186828aa3fac4c66ce6/grammar.js#L145-L150

2023-05-20 06:25 UTC, vkleen commented
I'll take care of that later today, thanks for diagnosing!

2023-05-20 15:55 UTC, pascalkuthe approved these changes

2023-05-26 07:22 UTC, the-mikedavis approved these changes

2023-05-26 07:23 UTC, merged