Add command to extend to line start or end
helix-editor/helix pull request #717
Opened 2021-09-06 10:00 UTC by pbzweihander

Currently, `goto_line_{start,end,end_newline}` commands works as `extend` when in select mode. This PR adds `extend_to_line_{start,end,end_newline}` commands that always extend to regardless of current mode.

2021-09-06 10:09 UTC, archseer requested changes

2021-09-06 10:09 UTC, archseer commented on helix-term/src/commands.rs
> +        range.put_cursor(text, pos, always_extend || doc.mode == Mode::Select)
I'd rather see this parameter called `extend`, then you can map to the new `extend_` commands inside the keymap https://github.com/helix-editor/helix/blob/918bde0b05ceef596283652a1c4c922f35f3921d/helix-term/src/keymap.rs#L577

(So two sets of commands, one that always moves, one that always extends)

2021-09-06 10:09 UTC, archseer commented on helix-term/src/commands.rs
> +        range.put_cursor(text, pos, always_extend || doc.mode == Mode::Select)
Even better than a bool would be if we reused this enum: https://github.com/helix-editor/helix/blob/3fda350494449bf5909a0b47f9e2f593fbe615ad/helix-core/src/movement.rs#L21-L25

2021-09-07 04:28 UTC, pbzweihander commented
@archseer I've updated PR!

2021-09-07 14:22 UTC, archseer approved these changes
Thanks! 🎉

2021-09-07 14:22 UTC, merged