WIP: smartcase search
helix-editor/helix pull request #761
Opened 2021-09-15 17:03 UTC by kraem

First stab at smartcase search.

Some thoughts:
- What's the desired behaviour for `select_regex`? Never enabled? Configured with a separate option?
- Where would the regex builder live in `helix-core`? (so it can be used for other ui:s than term and #651)

2021-09-16 06:09 UTC, archseer requested changes
> What's the desired behaviour for select_regex? Never enabled? Configured with a separate option?

Default it to `true`.

> Where would the regex builder live in helix-core? 

Let's skip this for now, this PR is just a temporary workaround until we switch over to regex-automata in https://github.com/helix-editor/helix/pull/211

2021-09-16 06:09 UTC, archseer commented on helix-term/src/ui/mod.rs
> +                    let case_insensitive = if cx.editor.config.smartcase { input == input.to_lowercase() } else { false };
This unnecessarily allocates, you want something like

```rust
input.chars().any(char::is_uppercase)
```

2021-09-16 06:09 UTC, archseer commented on helix-view/src/editor.rs
> +    pub smartcase: bool,
`smart-case`

2021-09-16 06:09 UTC, archseer commented on helix-view/src/editor.rs
> +    /// Smartcase: Case insensitive searching unless pattern has upper case character. Defaults to true.
```suggestion
    /// Smart case: Case insensitive searching unless pattern contains upper case characters. Defaults to true.
```

2021-09-16 19:32 UTC, kraem commented
Thanks :) Fixed your comments. Also took the liberty of removing the todo and a comment.

2021-09-18 02:45 UTC, archseer commented
Thanks! Looks like there's a conflict, and I'd also mention the new option in the configuration section of the book. Other than that it looks good for merge.

2021-09-20 04:44 UTC, archseer approved these changes

2021-09-20 04:45 UTC, merged