Add option for automatic insertion of closing-parens/brackets/etc
helix-editor/helix pull request #779
Opened 2021-09-22 03:21 UTC by lurpahi

This just makes it possible to turn off the automatic insertion of parentheses.

I assume `HOOKS` was `const` for a reason (maybe generating it is computationally expensive, so you wouldn't want it running on every key press?). So, instead of moving the definition of `HOOKS` to within the function it's used in, I added an alternative `HOOKS` without the auto-pair hook, and had the function determine which to use on the fly.

2021-09-22 14:46 UTC, pickfire approved these changes
Good job! Nice, finally I am waiting for this, I didn't know it's just a few lines of change. Not tested.

2021-09-23 04:45 UTC, archseer requested changes

2021-09-23 04:45 UTC, archseer commented on book/src/configuration.md
> +| `auto-pair` | Enable automatic insertion of pairs to parenthese, brackets, etc. | `true` |
Rename it to auto-pairs since that's the name we used for the feature

2021-09-23 04:45 UTC, archseer commented on helix-term/src/commands.rs
> +            true => HOOKS_PAIR,
You can inline the two consts here and remove the const definitions

2021-09-23 05:50 UTC, lurpahi commented
I feel like maybe I wasn't supposed to push that 're-request' button there. I don't know how to use this thing.
But, the requested changes have been made, and rustfmt seems to like it.

2021-09-23 08:36 UTC, archseer approved these changes

2021-09-24 01:28 UTC, merged

2021-09-24 01:28 UTC, archseer commented
Thanks!