feat: open file picker on directories using goto_file (gf)
helix-editor/helix pull request #7909
Opened 2023-08-11 12:16 UTC by cbr9

Closes #7906

2023-08-11 12:37 UTC, pascalkuthe requested changes
I think this makes sense. This makes `gf` matches `:open`

2023-08-11 12:37 UTC, pascalkuthe commented on helix-term/src/commands.rs
> +            if let Ok(path) = helix_core::path::get_canonicalized_path(path) {
you don't need to cannonicalize here

2023-08-11 12:37 UTC, pascalkuthe commented on helix-term/src/commands.rs
> +
adding a helper for two lines of code is really nod necessary and will cause merge conflicts with other changes to the picker

2023-08-15 02:26 UTC, the-mikedavis approved these changes

2023-08-15 07:32 UTC, pascalkuthe approved these changes

2023-08-15 07:37 UTC, merged