Adds calm book theme
helix-editor/helix pull request #8084
Opened 2023-08-27 22:03 UTC by LukeHalasy

2023-08-27 22:19 UTC, pascalkuthe requested changes

2023-08-27 22:19 UTC, pascalkuthe commented on runtime/queries/toml/highlights.scm
> +
there are theme key changes and even an unrelated (and incorrect) code change (which will cause build failures) bundled with this PR. A PR adding a theme should not contain such unrelated changes, please remove them

2023-08-27 22:19 UTC, pascalkuthe commented on runtime/queries/rust/highlights.scm
here

2023-08-27 22:19 UTC, pascalkuthe commented on helix-lsp/src/lib.rs
> +    workspace = true;
and here

2023-08-28 23:49 UTC, lukehalasy-anchorage commented
Hey @pascalkuthe .
My bad on creating this PR. I meant to create a PR within my fork, not to the main repo. Ill close this PR for now (though I do hope to contribute this theme at some point)

2023-08-28 23:50 UTC, closed without merging