Make sure pending key list is empty when count handling
helix-editor/helix pull request #8471
Opened 2023-10-06 01:32 UTC by areux

This will allow using numbers as second key event. Closes #8113

2023-10-06 17:26 UTC, the-mikedavis requested changes
I believe the solution for #8113 should be to look up the key event in the keymap before considering it for a count. If it's a possible keybinding (pending or command(s)) then it can just be used for the keybinding and if it isn't then it can be considered part of a count.

2023-10-06 17:26 UTC, the-mikedavis commented on helix-term/src/ui/editor.rs
> +                        }) =>
`g<n>g` can be remapped so this won't work robustly

2024-02-11 03:28 UTC, the-mikedavis requested changes
Sorry for the delay, this fell of my radar for a while. I have only some minor nits.

2024-02-11 03:28 UTC, the-mikedavis commented on helix-term/src/keymap.rs
> +    pub fn key_exists(&self, mode: Mode, key: KeyEvent) -> bool {
To fit with standard data structures like hashmap let's call this `contains_key`

2024-02-11 03:28 UTC, the-mikedavis commented on helix-term/src/keymap.rs
> +        keymap.search(&ks).is_some()
We can avoid the allocation of another vec for the pending keys here:

```suggestion
        keymap
            .search(self.pending())
            .and_then(KeyTrie::node)
            .is_some_and(|node| node.contains_key(&key))
```

2024-02-14 01:31 UTC, areux commented
Thanks for helping with this, I renamed the function and fixed the allocation issue.
I'm not familiar with helix source code, just followed what you said in your first comment and made these changes. I hope they're in the right places!

2024-02-14 01:51 UTC, the-mikedavis approved these changes
Thanks!

2024-02-14 10:53 UTC, pascalkuthe approved these changes

2024-02-14 10:53 UTC, merged