Reword on goto_change shortcut keys
helix-editor/helix pull request #8494
Opened 2023-10-09 03:27 UTC by hongquan

The old wording is confusing.

2023-10-09 12:34 UTC, leandrobbraga commented
I do believe that the idea of the previous naming is to be VCS agnostic

2023-10-09 12:44 UTC, hongquan commented
At first, I didn't understand what it means, until I found the blog post about Helix's Git support.
I think, in the future, when Helix supports more VCS, it can be named "Goto VCS change/hunk". For now, Helix only supports Git and it is more obvious to say "Go to Git hunk".

2023-10-09 15:34 UTC, pascalkuthe requested changes
* we Plan to support other VCS in the future so Git should not be mentioned explicitl
* we will allow diffing against arbitrary files and Buffets (a PR is already open) so it should not mention VCS either

These were designed goals from the start which is why I choose current description. The most I would co sidereal is to use `diff change` instead of `change`.

These also aren't the rendered docs. Those should be adjusted to match

2023-10-10 04:22 UTC, closed without merging

2023-10-10 04:22 UTC, hongquan commented
Thanks. I will close this PR and wait for Helix update.