Add LPF tree sitter
helix-editor/helix pull request #8536
Opened 2023-10-13 19:28 UTC by TheZoq2

Adds a small tree-sitter parser for the LPF configuration language https://github.com/danderson/ulxs/blob/main/lpf.md

2023-10-17 10:16 UTC, the-mikedavis reviewed
You can run `cargo xtask docgen` and commit the results to fix the docs CI

2023-10-17 10:16 UTC, the-mikedavis commented on runtime/queries/lpf/highlights.scm
> +["SITE"] @storage
```suggestion
["SITE"] @keyword.storage
```

to match https://docs.helix-editor.com/master/themes.html#syntax-highlighting

2023-10-26 15:11 UTC, the-mikedavis requested changes
Actually, looks like this still needs the change from `cargo xtask docgen`

2023-10-26 15:12 UTC, TheZoq2 commented
Yeah, sorry, I forgot to make that change. Give me a minute

2023-10-26 15:16 UTC, TheZoq2 commented
Fixed

2023-10-26 15:24 UTC, the-mikedavis approved these changes

2023-10-26 23:32 UTC, pascalkuthe approved these changes

2023-10-26 23:32 UTC, merged