language: added templ
helix-editor/helix pull request #8540
Opened 2023-10-15 00:45 UTC by rsteube

Added [templ](https://github.com/a-h/templ).

The captures probably still need some renaming.
Is the `structure.scm` needed?

[Quickstart](https://templ.guide/quick-start/creating-a-simple-templ-component)
[IDE Support](https://templ.guide/commands-and-tools/ide-support)

2023-10-17 10:21 UTC, the-mikedavis requested changes

2023-10-17 10:21 UTC, the-mikedavis commented on runtime/queries/templ/highlights.scm
> +(element_comment) @comment @spell
```suggestion
(comment) @comment

(element_comment) @comment
```

2023-10-17 10:21 UTC, the-mikedavis commented on runtime/queries/templ/highlights.scm
> +  name: (identifier) @definition.function)
```suggestion
  name: (identifier) @function)
```

2023-10-17 10:21 UTC, the-mikedavis commented on runtime/queries/templ/highlights.scm
> +(type_spec name: (type_identifier) @type.definition)
```suggestion
(type_spec name: (type_identifier) @type)
```

2023-10-17 10:21 UTC, the-mikedavis commented on runtime/queries/templ/highlights.scm
> +(field_identifier) @property
```suggestion
(field_identifier) @variable.other.member
```

2023-10-17 10:21 UTC, the-mikedavis commented on runtime/queries/templ/highlights.scm
> +    field: (field_identifier) @reference.call))
```suggestion
  function: (identifier) @function)

(call_expression
  function: (selector_expression
    field: (field_identifier) @function))
```

2023-10-17 10:21 UTC, the-mikedavis commented on runtime/queries/templ/highlights.scm
> +] @keyword.storate.type
```suggestion
] @keyword.storage.type
```

2023-10-17 10:21 UTC, the-mikedavis commented on runtime/queries/templ/structure.scm
This can be removed

2023-10-17 10:52 UTC, the-mikedavis commented
It looks like the tree-sitter-templ scanner.c causes has some compilation errors on Windows

2023-10-17 14:18 UTC, rsteube commented
```c
  D:\a\helix\helix\runtime\grammars\sources\templ\src\scanner.c(67): warning C4189: 'found': local variable is initialized but not referenced
  D:\a\helix\helix\runtime\grammars\sources\templ\src\scanner.c(93): error C2016: C requires that a struct or union have at least one member
  D:\a\helix\helix\runtime\grammars\sources\templ\src\scanner.c(341): warning C4244: 'function': conversion from 'int32_t' to 'wint_t', possible loss of data
```

Is it related to https://github.com/vrischmann/tree-sitter-templ/blob/master/src/scanner.c#L93 not having any member?
Or is that error just a warning and something other causes the failed build?

2023-10-18 08:45 UTC, the-mikedavis commented
Yep, I believe the warnings are benign but the error from the line you linked stops compilation

2023-10-21 09:07 UTC, the-mikedavis reviewed
Just a minor note in the languages.toml, otherwise I think this looks good

2023-10-21 09:07 UTC, the-mikedavis commented on languages.toml
> +grammar = "templ"
This key can be eliminated - when it is omitted the name of the language is used by default

2023-10-21 09:41 UTC, the-mikedavis approved these changes

2023-10-21 09:46 UTC, pascalkuthe approved these changes

2023-10-21 12:15 UTC, merged