feat: add picker config
helix-editor/helix pull request #8561
Opened 2023-10-17 19:04 UTC by zaucy

2023-10-17 19:18 UTC, pascalkuthe requested changes
Config options should never be used to configure themen keys. If you want to change the way the picker looks change theme.

2023-10-17 19:29 UTC, zaucy commented
@pascalkuthe understood. I removed the style options and kept `picker.highlight-symbol`.

2023-10-18 08:44 UTC, the-mikedavis commented
I would prefer that we be opinionated rather than configurable for small display items like this - this seems unnecessary to me

2023-10-18 15:16 UTC, zaucy commented
I understand. My motiviation is that on my fork of helix I have icons and a different look for selection that the " > " doesn't really fit well with. I want it to be empty ("").

![image](https://github.com/helix-editor/helix/assets/1284289/97245998-e5dc-4e72-807a-7d85b09acddf)

2023-10-19 12:04 UTC, pascalkuthe commented
If you have your own fork anyway then you can simply patch the indicator there. I don't think it makes sense as an option in core. We try to keep co fig options to a minimum

2023-10-19 12:04 UTC, closed without merging