fix: typo in multiple files
helix-editor/helix pull request #8630
Opened 2023-10-27 02:09 UTC by thapasusheel

This PR fix the typos seen in multiple files

```pseudo
continous > continuous
indecies > indicies
posible > possible
thhis > this
reeplace > replace
witth > with
```

2023-10-27 02:15 UTC, gabydd requested changes

2023-10-27 02:15 UTC, gabydd commented on runtime/queries/_typescript/highlights.scm
> +; (p?: t = 1) // Invalid but still possible to hihglight.
Highlight is also miss spelled in a couple places in this file

2023-10-27 02:15 UTC, gabydd commented on runtime/tutor
> + --> Fiix the errors on this line and replace them with undo.
These errors are meant to be there see the tutor task the snippet is for

2023-10-27 02:28 UTC, thapasusheel commented
@gabydd  I have made changes as per you have requested. Can you please review it?

2023-10-27 02:36 UTC, gabydd approved these changes

2023-10-27 12:37 UTC, uncenter commented
A couple more typos you could fix here (or I can do em in a separate PR):
- https://github.com/helix-editor/helix/blob/master/helix-core/src/transaction.rs#L343 (usally -> usually)
- https://github.com/helix-editor/helix/blob/master/helix-core/src/transaction.rs#L860 (stays ~~inbetween~~ **in between** replacements
- https://github.com/helix-editor/helix/blob/master/helix-term/src/commands.rs#L2243 (continous -> continuous)
- https://github.com/helix-editor/helix/blob/master/helix-term/src/keymap.rs#L267 (upto -> up to)
- https://github.com/helix-editor/helix/blob/master/runtime/queries/nix/injections.scm#L4 (arbitary -> arbitrary)

These aren't comments but "definition" is spelled wrong here? https://github.com/helix-editor/helix/blob/master/runtime/queries/rescript/locals.scm#L6-L7.

2023-10-27 15:20 UTC, the-mikedavis requested changes
See https://github.com/helix-editor/helix/pull/8233#pullrequestreview-1618903465

The typos in the highlights are all ok to be fixed but let's avoid touching the rust files here, it will just introduce conflicts for open PRs that touch these blocks. In PRs where I refactor the picker and global search and already change these lines, I have these typos fixed.

2023-10-27 15:37 UTC, uncenter commented
Alright, makes sense!

2023-10-28 01:07 UTC, thapasusheel commented
> See [#8233 (review)](https://github.com/helix-editor/helix/pull/8233#pullrequestreview-1618903465)
> 
> The typos in the highlights are all ok to be fixed but let's avoid touching the rust files here, it will just introduce conflicts for open PRs that touch these blocks. In PRs where I refactor the picker and global search and already change these lines, I have these typos fixed.

I have made the necessary change can you review it again?

2023-10-29 16:42 UTC, the-mikedavis commented
Yeah we run into this piece of advice every now and then even for non-typo-like changes (e.g. renaming structs, making formatting changes, etc.). I'll add a PR with a note about that

2023-10-29 16:42 UTC, the-mikedavis approved these changes

2023-10-29 16:43 UTC, the-mikedavis commented
It'd be nice to fix the typos in the locals queries as well (in this PR or separately): https://github.com/helix-editor/helix/blob/f992c3b5972dbe2432ceb55bc8d47fed912f88bf/runtime/queries/rescript/locals.scm#L6-L7. That typo is causing a small bug in the rescript highlighting.

2023-12-15 06:58 UTC, merged