Added Hoon
helix-editor/helix pull request #9024
Opened 2023-12-07 03:42 UTC by ilyakooo0

2023-12-07 15:43 UTC, the-mikedavis reviewed
Helix needs queries under `runtime/queries/hoon/highlights.scm` in order to provider syntax highlighting: https://docs.helix-editor.com/master/guides/adding_languages.html#queries

2023-12-07 15:43 UTC, the-mikedavis commented on languages.toml
> +grammar = "hoon"
This key can be omitted since the `[[grammar]]` entry uses the same name as the `[[language]]` name

2023-12-07 15:43 UTC, the-mikedavis commented on languages.toml
> +roots = []
This line can be removed now that we default this field: https://github.com/helix-editor/helix/pull/8803

2023-12-08 19:06 UTC, the-mikedavis commented on runtime/queries/hoon/highlights.scm
> +(number) @number
```suggestion
(number) @constant.numeric
```

We use some custom capture names: https://docs.helix-editor.com/master/themes.html#syntax-highlighting

2023-12-08 19:06 UTC, the-mikedavis commented on runtime/queries/hoon/highlights.scm
> +(boolean) @constant.builtin
```suggestion
(boolean) @constant.builtin.boolean
```

2023-12-08 20:28 UTC, gabydd requested changes

2023-12-08 20:28 UTC, gabydd commented on languages.toml
> +source = { git = "https://github.com/urbit-pilled/tree-sitter-hoon", rev = "1d5df35af3e0afe592832a67b9fb3feeeba1f7b6" }
Can you move this below the language definition so it's formatted the same as the other languages

2023-12-09 01:35 UTC, gabydd commented
Looks like there is a language server: https://github.com/urbit/hoon-language-server might be nice to add the config for it if it works and add it to the wiki. If not that's not a blocker

2023-12-09 02:18 UTC, ilyakooo0 commented
Running the language server isn't as simple as running a binary at the root of the project. There's more setup involved. 

From what I heard the language server doesn't work that well and nobody actually uses it.

2023-12-09 03:59 UTC, gabydd approved these changes

2023-12-10 19:10 UTC, the-mikedavis approved these changes

2023-12-27 15:20 UTC, the-mikedavis commented on languages.toml
>  name = "janet"
It looks like the merge cut off some lines. The `Hoon` line at the top here can be removed and the `name = "janet"` line should have a line that says `[[language]]` above it

2023-12-30 12:41 UTC, closed without merging