Add initial support for SuperCollider
helix-editor/helix pull request #9329
Opened 2024-01-13 01:30 UTC by pnelson

Implements syntax highlighting for SuperCollider. See also #7368.

2024-01-15 19:07 UTC, the-mikedavis requested changes

2024-01-15 19:07 UTC, the-mikedavis commented on runtime/queries/supercollider/highlights.scm
> +; See this for full list: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md
Helix uses different capture names than neovim. See https://docs.helix-editor.com/master/themes.html#syntax-highlighting

For example captures like `parameter` need to become `variable.parameter`, `property` becomes `variable.other.member`, etc.

2024-01-15 19:07 UTC, the-mikedavis commented on runtime/queries/supercollider/indents.scm
Helix also has a custom indentation system that these queries will need to be rewritten for, see https://docs.helix-editor.com/master/guides/indent.html

2024-01-15 19:07 UTC, the-mikedavis commented on runtime/queries/supercollider/locals.scm
For locals we follow tree-sitter: https://tree-sitter.github.io/tree-sitter/syntax-highlighting#local-variables

so there should only be the captures `local.scope`, `local.definition` and `local.reference`

2024-01-18 02:12 UTC, pnelson commented
I touched up the `highlights.scm` and it's looking good when I run it on [tutorial.scd](https://raw.githubusercontent.com/igramjp/supercollider/master/tutorial.scd) but really struggled with the other tree-sitter files. Are highlights-only an acceptable breakpoint for this PR?

2024-01-18 14:46 UTC, the-mikedavis submitted a review, later dismissed

2024-01-18 14:47 UTC, the-mikedavis commented
Yep highlights-only is a good start :+1:. The other queries can be contributed as follow-ups if anyone is interested in working on them

2024-02-05 14:12 UTC, the-mikedavis submitted a review, later dismissed

2024-03-17 23:07 UTC, pascalkuthe submitted a review, later dismissed

2024-03-17 23:08 UTC, pascalkuthe commented
needs a rebase

2024-03-18 11:54 UTC, the-mikedavis approved these changes

2024-03-18 12:13 UTC, merged