Disable loading of workspace configs by default and make it configurable
helix-editor/helix pull request #9545
Opened 2024-02-06 04:09 UTC by the-dipsy

Makes loading of workspace-local `config.toml` and `languages.toml` files optional and disables it by default to protect against vulnerability to arbitrary code execution when running helix in an untrusted directory. Should fix #9514 and alleviate #2697.

2024-02-06 06:16 UTC, the-mikedavis requested changes
I'm not sure if we will want this behavior once we have workspace trust. Instead I think we will want the opposite: the ability to say that you never want to be prompted about workspace trust and never use workspace config. (So the default would be the opposite: that you do merge workspace configs but only when you trust the workspace.)

2024-02-06 06:17 UTC, archseer commented on languages.toml
> +workspace-config = false
Additionally, `workspace-config` should not be in languages.toml.

2024-02-06 12:00 UTC, the-dipsy commented
@the-mikedavis I'd be fine with your workspace trust concept once it is implemented and if the prompt is absolutely clear about the risks. I'd really like the ability to activate language servers and loading of workspace configs separately though.

2024-02-06 12:04 UTC, pascalkuthe commented
> I'd really like the ability to activate language servers and loading of workspace configs separately though.

that ssesm like security theater to me.  VSCode doesn't do that either. If you trust the LSP you trust the config. The other way around you can disable LSP in your workspace config.

2024-02-06 12:16 UTC, the-dipsy commented
@archseer There is one `workspace-config = true` for `config.toml` and one for `languages.toml`. The current code structure makes it way easier to implement this way and I think it makes sense too :shrug:

2024-02-06 12:29 UTC, the-dipsy commented on helix-term/src/config.rs
> +        mut global: ConfigRaw, mut workspace: Option<ConfigRaw>,
I wanted to change as little as possible but I'm all for cleaning stuff up a little. Is `Config::load_default` even the right name for what it's doing? I would expect `load_default` to only load the config shipped with the package or at least only the global config.

2024-02-06 12:34 UTC, the-dipsy commented on helix-loader/src/config.rs
> +    let config = match global.get("workspace-config").and_then(|v| v.as_bool()) {
How would you implement that with the current code structure? Loading the entire config a second time seems wasteful but the current control flow doesn't seem to make it trivial to pass a parameter loaded from the `config.toml` to the code that loads the `languages.toml`.

2024-02-06 12:55 UTC, the-dipsy commented
@pascalkuthe It seems entirely reasonable to me to have language servers statically analyze code, provide snippets etc. without opening up the gates for ACE :flushed: I'm not a heavy user of language servers but this is what GPT-4 says about it:

**User:** How common is unprotected execution of code from currently edited code repositories in language servers used in IDEs?
**GPT-4:** Unprotected execution of code from currently edited repositories in language servers is not common and is generally considered a security risk. Language servers typically provide features like code analysis, linting, autocomplete, and refactoring. They parse the code and understand its structure, but they do not execute the actual code being edited. When execution is necessary, for example, during debugging sessions, it is done in a controlled environment, often with explicit user consent and understanding of the risks.

I'd assume that a lot of people who switch to a small-code-base editor that doesn't rely on plugins, advertises to be usable over SSH, and is implemented in a security-driven language expect it to follow a security-conscious approach and configurability.

2024-02-06 13:04 UTC, pascalkuthe commented
gpt is not a reliable source for *anything* and as usual provides a wordsoup without substance.

The majority of languageserver will execute arbitrary code which is why vscode disables them by default. For example rust-analyzer will execute all "build.rs" files and procedural macros (yes without any sandboxing). They often even have their own config files which they read from the project from which they can and do execute commands.

2024-02-06 13:35 UTC, the-dipsy commented
@pascalkuthe Certainly no proof and unreliable but often decent at reiterating and summarizing information. I know that rust does this but it therefore is also pretty much the first thing that comes up when putting "language server" and "arbitrary code execution" into a search engine. I don't have a reliable source that says *most* LSPs don't do this. Do you have a source for the opposite? Jedi [apparently is one explicit example](https://jedi.readthedocs.io/en/latest/docs/features.html#for-script). In any case, the fact that there are plenty of ways to use the language server protocol without arbitrary code execution warrants an option to use them that way IMO.

2024-02-06 13:44 UTC, the-mikedavis commented on helix-term/src/config.rs
> +        mut global: ConfigRaw, mut workspace: Option<ConfigRaw>,
I believe these changes will make workspace trust easier to add so it seems like a worthwhile refactor anyways. Yeah I think we could rename `load_default` as `load` and that would make more sense

2024-02-06 14:00 UTC, the-mikedavis commented on helix-loader/src/config.rs
> +    let config = match global.get("workspace-config").and_then(|v| v.as_bool()) {
I think the only option is passing down a boolean parameter. IIRC we always load normal config before language config so it should be possible to read this only from `config.toml`

2024-02-06 14:19 UTC, the-mikedavis reviewed
I'm not keen to accept this as-is: we usually do not accept "bandaid" fixes that work around missing features, especially when we would have to remove them or make breaking changes to them later as we would with workspace trust. IMO this is not a very serious threat and seems mostly theoretical so it would be an overreaction to hot-fix it that leaves us with annoying defaults, a lot like git's `safe.directory` response to [cve-2022-24765](https://github.blog/2022-04-12-git-security-vulnerability-announced/#cve-2022-24765) (reiterating what I was saying [here](https://github.com/helix-editor/helix/pull/3207#issuecomment-1257309846)).

But I think this PR could be a really good base for the changes we need for workspace trust and could be merged before that is introduced with a small change: let's switch the `workspace_config: bool` option out for an enum

```rust
#[derive(Default)]
pub enum LoadWorkspaceConfig {
	Always,
    #[default]
    Never,
}
```

which you would write in config as `"always"` or `"never"`. Workspace trust would add a `Trust` variant that should become the default. That way you can decide what behavior you want: always or never load workspace configs, and the meaning of these options doesn't change at all once workspace trust is added.

2024-02-06 14:45 UTC, archseer commented
I pushed my set of changes based on some comments above here: https://github.com/helix-editor/helix/commit/5ed223f9476810a65c427c464d99950f1df6ec49

2024-02-06 19:14 UTC, the-dipsy commented
@archseer Oh, shoot. I refactored a bunch already. My config merging is not particularly clean yet though.

2024-02-06 22:03 UTC, the-dipsy commented
@archseer Oh, shoot. I refactored a bunch already. Is my version okay for you?

2024-02-06 22:38 UTC, the-dipsy commented on helix-term/src/config.rs
> +        mut global: ConfigRaw, mut workspace: Option<ConfigRaw>,
Should be done now.

2024-12-04 17:42 UTC, closed without merging

2025-07-06 14:53 UTC, LennyPenny commented
@the-dipsy what happened to this PR? Is possible to configure helix to be secure by default now in some other way?

2025-07-06 15:00 UTC, the-dipsy commented
> @the-dipsy what happened to this PR? Is possible to configure helix to be secure by default now in some other way? 

I didn't continue adapting my solution to the requirements by the core devs and thus it was never merged. I haven't followed the progress of the workspace trust feature envisioned by them. If it hasn't been finished yet, this ACE vulnerability probably still persists.