[Rust] Added fields as argument textobject (#9155)
helix-editor/helix pull request #9637
Opened 2024-02-15 18:21 UTC by uek-1

Added struct field declarations and initializations as argument textobjects. Should allow ]a to highlight fields in structs. Addresses #9155. Let me know if I messed anything up, this is my first real commit to an open source project.

2024-02-15 19:06 UTC, the-mikedavis requested changes
I could see `field_initializer_list` roughly fitting into the argument/parameter textobject but `field_declaration_list` should be removed

2024-02-16 19:38 UTC, uek-1 commented
I removed `field_declaration_list ` .

2024-02-17 14:57 UTC, the-mikedavis approved these changes
Thanks!

2024-02-17 16:08 UTC, pascalkuthe approved these changes

2024-02-17 16:08 UTC, merged