Fix crash on LSP text edits with invalid ranges
helix-editor/helix pull request #9649
Opened 2024-02-17 15:07 UTC by skyl4b

This PR attempts to fix #9624.

While testing helix-gpt out, helix crashed many times for me. I decided to take a shot at fixing this issue myself, with a simple check inside the Transaction change edit's closure. When the range is invalid, I simply discarded the edit and logged it.

As noted in the issue, this is mainly a problem inside helix-gpt itself, but a crash is undesirable.

2024-02-17 15:17 UTC, the-mikedavis approved these changes
There's also an `lsp_range_to_range` helper that handles this case, but it handles it by capping `range.start` to `range.end`. I think discarding the edit makes more sense in this case. What do you think @pascalkuthe?

2024-02-17 16:06 UTC, pascalkuthe requested changes
Invalid completions already have some logic dedicated to them and I would like to check that there isn't some new bug here.

2024-03-04 22:52 UTC, skyl4b commented
If there's anything else I can do to help with this issue, please let me know.

2024-04-06 02:17 UTC, pascalkuthe approved these changes

2024-04-06 02:17 UTC, merged