feat(book/src/languages.md)
helix-editor/helix pull request #979
Opened 2021-11-04 17:42 UTC by ammkrn

Add a section in the book about language-specific settings and the languages.toml file.

2021-11-04 18:02 UTC, sudormrfbin commented on book/src/languages.md
> +Language-specific settings and settings for particular language servers can be configured in a `languages.toml` file placed in your configuration directory (e.g. `~/.config/helix/languages.toml`). An
```suggestion
Language-specific settings and settings for particular language servers can be configured in a `languages.toml` file placed in your [configuration directory](./configuration.md). An example which includes the defaults used by helix can be found in the main helix repository's [languages.toml](https://github.com/helix-editor/helix/blob/master/languages.toml) file.
```

2021-11-05 01:08 UTC, archseer commented
Would you mind merging in some of the text from https://github.com/helix-editor/helix/pull/710 ?

2021-11-05 02:26 UTC, ammkrn commented
> Would you mind merging in some of the text from #710 ?

@archseer It doesn't look like the question about what `roots` is for was ever resolved. I only added the configuration page because I couldn't figure out how to turn off auto-format and language configuration wasn't in the docs. Adding a new language to the compile-time toml file seems more involved, I'll probably put it in a separate section.

2021-11-05 18:58 UTC, ammkrn commented
@archseer `adding_languages` is now included, as well as the suggested changes from the #710 discussion. Someone's still on the hook for a description of `roots`.

2021-11-06 11:56 UTC, archseer requested changes
Looks great! Two small tweaks:

2021-11-06 11:56 UTC, archseer commented on book/src/languages.md
> +
Actually, the configs get merged with defaults now so it's enough only override `auto-format`:

```toml
[[language]]
name = "rust"
auto-format = false
```

2021-11-06 11:56 UTC, archseer commented on book/src/guides/adding_languages.md
> +| roots         | description TBD                                               |
```suggestion
| roots         | A set of marker files to look for when trying to find the workspace root. For example `Cargo.lock`, `yarn.lock` |
```

2021-11-06 11:56 UTC, archseer commented on book/src/guides/adding_languages.md
> +| indent        | The indent to use. Has sub keys tab-width and unit            |
```suggestion
| indent        | The indent to use. Has sub keys `tab-width` and `unit`            |
```

2021-11-06 15:18 UTC, ammkrn commented
@archseer 

The formatting suggestions are incorporated and the languages.md page was rewritten to mention the merge behavior as well as the role of both languages.toml files.

2021-11-07 01:31 UTC, archseer commented
Thanks, documentation improvements are always great! 🎉

2021-11-07 01:31 UTC, merged